name: react React+TS+Vite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'Installing deps'    
      run: yarn
    - name: 'Build'
      run: yarn build
    - name: 'Move'
      run: mkdir -p _site/ocr-landing && find _site -maxdepth 1 -type f -exec mv {} _site/ocr-landing/ \;
    - name: 'Deploy'
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./_site
        allow_empty_commit: true
